quarkus.http.port=8090
quarkus.http.host=localhost
quarkus.http.test-port=8093

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] [corrId=%X{correlationId}] [thread=%t] %s%e%n

quarkus.smallrye-openapi.enabled=true
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.version=1.0.0
quarkus.smallrye-openapi.title=ShopFlow Gateway API
quarkus.smallrye-openapi.description=API Gateway for the ShopFlow platform

quarkus.rest-client."com.example.gateway.client.OrderServiceClient".url=http://localhost:8080
quarkus.rest-client."com.example.gateway.client.OrderServiceClient".scope=jakarta.inject.Singleton

%prod.quarkus.http.host=0.0.0.0
%prod.quarkus.rest-client."com.example.gateway.client.OrderServiceClient".url=http://order-service:8080
