quarkus.http.port=8082
app.inventory.accepted=true
app.inventory.crash=false
app.inventory.delay=0

smallrye.jwt.path.groups=realm_access/roles
%dev.mp.jwt.verify.issuer=http://localhost:8180/realms/shopflow
%dev.mp.jwt.verify.publickey.location=http://localhost:8180/realms/shopflow/protocol/openid-connect/certs
%prod.mp.jwt.verify.issuer=http://localhost:8180/realms/shopflow
%prod.mp.jwt.verify.publickey.location=http://keycloak:8080/realms/shopflow/protocol/openid-connect/certs
quarkus.log.console.format=%d{HH:mm:ss} %-5p [inventory-service] [%c{1}] [corrId=%X{correlationId}] [orderId=%X{orderId}] %s%e%n
quarkus.kafka.devservices.shared=true

# ─── Schema Registry ───────────────────────────────────────────────────────────
quarkus.apicurio-registry.devservices.port=8091
quarkus.apicurio-registry.devservices.shared=true
%prod.kafka.bootstrap.servers=kafka:9092
%prod.mp.messaging.connector.smallrye-kafka.apicurio.registry.url=http://apicurio-registry:8080

# ─── Producers ─────────────────────────────────────────────────────────────────
mp.messaging.outgoing.inventory-approved.connector=smallrye-kafka
mp.messaging.outgoing.inventory-approved.topic=inventory-approved
mp.messaging.outgoing.inventory-approved.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.inventory-approved.apicurio.registry.auto-register=true
mp.messaging.outgoing.inventory-approved.apicurio.registry.artifact-id=inventory-approved-value

mp.messaging.outgoing.inventory-rejected.connector=smallrye-kafka
mp.messaging.outgoing.inventory-rejected.topic=inventory-rejected
mp.messaging.outgoing.inventory-rejected.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.inventory-rejected.apicurio.registry.auto-register=true
mp.messaging.outgoing.inventory-rejected.apicurio.registry.artifact-id=inventory-rejected-value

# ─── Consumers ─────────────────────────────────────────────────────────────────
mp.messaging.incoming.inventory-request.connector=smallrye-kafka
mp.messaging.incoming.inventory-request.topic=inventory-request
mp.messaging.incoming.inventory-request.group.id=inventory-service
mp.messaging.incoming.inventory-request.value.deserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer
mp.messaging.incoming.inventory-request.apicurio.registry.use-specific-avro-reader=true
mp.messaging.incoming.inventory-request.failure-strategy=dead-letter-queue
mp.messaging.incoming.inventory-request.dead-letter-queue.topic=inventory-request-dlq
mp.messaging.incoming.inventory-request.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.incoming.inventory-request.max-retries=5
mp.messaging.incoming.inventory-request.retry-backoff.initial=1s
mp.messaging.incoming.inventory-request.retry-backoff.max=30s
mp.messaging.incoming.inventory-request.retry-backoff.factor=2.0
