INSERT INTO products (id, artist, title, price, image_url) VALUES
    (gen_random_uuid(), 'Pink Floyd',   'Animals',                         36.99, '/assets/covers/classic-rock/pink-floyd-animals.jpg'),
    (gen_random_uuid(), 'Black Sabbath','Vol. 4',                          31.99, '/assets/covers/classic-rock/black-sabbath-vol4.jpg'),
    (gen_random_uuid(), 'The Beatles',  'Abbey Road',                      38.99, '/assets/covers/classic-rock/beatles-abbey-road.jpg'),
    (gen_random_uuid(), 'Led Zeppelin', 'IV',                              34.99, '/assets/covers/classic-rock/led-zeppelin-iv.jpg'),
    (gen_random_uuid(), 'King Crimson', 'In the Court of the Crimson King',39.99, '/assets/covers/classic-rock/king-crimson-in-the-court.jpg'),
    (gen_random_uuid(), 'AC/DC',        'Let There Be Rock',               29.99, '/assets/covers/classic-rock/acdc-let-there-be-rock.jpg'),
    (gen_random_uuid(), 'Thin Lizzy',   'Jailbreak',                       32.99, '/assets/covers/classic-rock/thin-lizzy-jailbreak.jpg'),
    (gen_random_uuid(), 'Budgie',       'Squawk',                          29.99, '/assets/covers/classic-rock/budgie-squawk.jpg'),
    (gen_random_uuid(), 'Deep Purple',  'Machine Head',                    33.99, '/assets/covers/classic-rock/deep-purple-machine-head.jpg'),
    (gen_random_uuid(), 'Motörhead',    '1916',                            31.99, '/assets/covers/classic-rock/motorhead-1916.jpg'),
    (gen_random_uuid(), 'Dire Straits', 'Making Movies',                   33.99, '/assets/covers/classic-rock/dire-straits-making-movies.jpg'),
    (gen_random_uuid(), 'Rolling Stones','Sticky Fingers',                 35.99, '/assets/covers/classic-rock/rolling-stones-sticky-fingers.jpg'),
    (gen_random_uuid(), 'Cream',        'Disraeli Gears',                  32.99, '/assets/covers/classic-rock/cream-disraeli-gears.jpg'),
    (gen_random_uuid(), 'Led Zeppelin', 'Physical Graffiti',               36.99, '/assets/covers/classic-rock/led-zeppelin-physical-graffiti.jpg'),
    (gen_random_uuid(), 'Pink Floyd',   'The Dark Side Of The Moon',       38.99, '/assets/covers/classic-rock/pink-floyd-the-dark-side-of-the-moon.jpg'),
    (gen_random_uuid(), 'Jethro Tull',  'Aqualung',                        33.99, '/assets/covers/classic-rock/jethro-tull-aqualung.jpg'),
    (gen_random_uuid(), 'Mountain',     'Climbing!',                       29.99, '/assets/covers/classic-rock/mountain-climbing.jpg'),
    (gen_random_uuid(), 'Black Sabbath','Master Of Reality',               31.99, '/assets/covers/classic-rock/black-sabbath-master-of-reality.jpg'),
    (gen_random_uuid(), 'Budgie',       'Bandolier',                       28.99, '/assets/covers/classic-rock/budgie-bandolier.jpg'),
    (gen_random_uuid(), 'The Who',      'Who''s Next',                     34.99, '/assets/covers/classic-rock/the-who-whos-next.jpg');