quarkus.http.port=8082
quarkus.kafka.devservices.shared=true

# Producer → send result
mp.messaging.outgoing.restaurant-approved.connector=smallrye-kafka
mp.messaging.outgoing.restaurant-approved.topic=restaurant-approved
mp.messaging.outgoing.restaurant-approved.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.restaurant-rejected.connector=smallrye-kafka
mp.messaging.outgoing.restaurant-rejected.topic=restaurant-rejected
mp.messaging.outgoing.restaurant-rejected.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Consumer → receive order
mp.messaging.incoming.restaurant-request.connector=smallrye-kafka
mp.messaging.incoming.restaurant-request.topic=restaurant-request
mp.messaging.incoming.restaurant-request.group.id=restaurant-service
mp.messaging.incoming.restaurant-request.failure-strategy=dead-letter-queue
mp.messaging.incoming.restaurant-request.dead-letter-queue.topic=restaurant-request-dlq
mp.messaging.incoming.restaurant-request.max-retries=5
mp.messaging.incoming.restaurant-request.retry-backoff.initial=1s
mp.messaging.incoming.restaurant-request.retry-backoff.max=30s
mp.messaging.incoming.restaurant-request.retry-backoff.factor=2.0
mp.messaging.incoming.restaurant-request.value.deserializer=io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
mp.messaging.incoming.restaurant-request.value.deserializer.value-type=com.example.shared.events.RestaurantRequestEvent
